### ISSUE TITLE
Cloud-init keeps giving error during reboots

### ISSUE THREAD

**Issue by Duvel** [hypriot/image-builder-rpi#232]
I found that cloud-init keeps executing my cloud-init file at every boot. After the first reboot I see these errors in /var/cloud/cloud-init.log:

```
2018-03-28 12:19:06,499 - handlers.py[DEBUG]: finish: init-local/check-cache: FAIL: attempting to read from cache [check]
2018-03-28 12:19:06,500 - util.py[WARNING]: failed stage init-local
2018-03-28 12:19:06,501 - util.py[DEBUG]: failed stage init-local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 513, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 236, in main_init
    init.fetch(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 342, in fetch
    return self._get_data_source(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 237, in _get_data_source
    ds, desc = self._restore_from_checked_cache(existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 223, in _restore_from_checked_cache
    ds.check_instance_id(self.cfg)):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceNoCloud.py", line 184, in check_instance_id
    quick_id = _quick_read_instance_id(dirs=dirs)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceNoCloud.py", line 212, in _quick_read_instance_id
    if iid_key in md:
TypeError: argument of type 'NoneType' is not iterable
```

You can solve this error setting for instance ```instance-id: pirate001``` in the meta-data file.

**Comment by StefanScherer** [comment]
I've seen these errors as well. Thanks. 
The instance-id is normally per device, but we only use a local user-data/meta-data pair. A fixed default instance-id should do it and users can change it in /boot/meta-data and overwrite the file with `flash -m` option.
