### ISSUE TITLE
Python error messages after first boot with wifi

### ISSUE THREAD

**Issue by guidoffm** [hypriot/image-builder-rpi#238]
For Hypriot image 1.8.0 on Raspi 3:

I have added the the information for wlan0 in user-data.

The first boot runs without errors and the wlan0 interface is correctly configured.

After the first boot cloud-init gives python errors on every boot but wlan0 still works.
```
[   16.312917] cloud-init[196]: Cloud-init v. 0.7.9 running 'init-local' at Sat, 31 Mar 2018 00:07:22 +0000. Up 15.72 seconds.
[   16.315123] cloud-init[196]: 2018-03-31 00:07:23,446 - util.py[WARNING]: failed stage init-local
[   16.340681] cloud-init[196]: failed run of stage init-local
[   16.342691] cloud-init[196]: ------------------------------------------------------------
[   16.344458] cloud-init[196]: Traceback (most recent call last):
[   16.346047] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 513, in status_wrapper
[   16.347614] cloud-init[196]:     ret = functor(name, args)
[   16.349096] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 236, in main_init
[   16.360932] cloud-init[196]:     init.fetch(existing=existing)
[   16.366995] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 342, in fetch
[   16.368525] cloud-init[196]:     return self._get_data_source(existing=existing)
[   16.370069] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 237, in _get_data_source
[   16.371695] cloud-init[196]:     ds, desc = self._restore_from_checked_cache(existing)
[   16.373327] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 223, in _restore_from_checked_cache
[   16.375298] cloud-init[196]:     ds.check_instance_id(self.cfg)):
[   16.376939] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceNoCloud.py", line 184, in check_instance_id
[   16.383505] cloud-init[196]:     quick_id = _quick_read_instance_id(dirs=dirs)
[   16.385176] cloud-init[196]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceNoCloud.py", line 212, in _quick_read_instance_id
[   16.386940] cloud-init[196]:     if iid_key in md:
[   16.388570] cloud-init[196]: TypeError: argument of type 'NoneType' is not iterable
[   16.395171] cloud-init[196]: ------------------------------------------------------------
[FAILED] Failed to start Initial cloud-init job (pre-networking).
```
The user-data file reads:
```
#cloud-config
# vim: syntax=yaml
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.6
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: rsp2
manage_etc_hosts: true

# You could modify this for your own user information
users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

# # Set the locale of the system
# locale: "en_US.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
# timezone: "America/Los_Angeles"

# # Update apt packages on first boot
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true
package_upgrade: false

# # Install any additional apt packages you need here
# packages:
#  - ntp

# WiFi connect to HotSpot
# - use `wpa_passphrase SSID PASSWORD` to encrypt the psk
write_files:
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=de
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid="xxxxxx"
      psk="xxxxxxxxxxxxxxxxx"
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'

  # Activate WiFi interface
  - 'ifup wlan0'
```

**Comment by StefanScherer** [comment]
Duplicate. See #232 for a fix in /boot/meta-data file. There will be a fix in 1.8.1.
